format = """
[ 🖿 ](bg:#5B3D7B fg:#D1A6D6)\
$directory\
[](fg:#5B3D7B bg:#6A4C9C)\
$git_branch\
$git_status\
[](fg:#6A4C9C bg:#7A4BCF)\
[ $cmd_duration ](bg:#7A4BCF fg:#E1D9F0)\
[ ](fg:#7A4BCF)\
"""

[directory]
style = "bg:#5B3D7B fg:#E1D9F0"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "⋯/"
truncate_to_repo = false
home_symbol = "~"

[git_branch]
symbol = ""
style = "bg:#6A4C9C fg:#E1D9F0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6A4C9C fg:#E1D9F0"
format = '[$all_status$ahead_behind ]($style)'

[cmd_duration]
min_time = 100
format = "$duration"
style = "bg:#7A4BCF fg:#E1D9F0"
show_milliseconds = false

